services:
  frontend:
    container_name: react_router
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
      - db
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/

  server:
    container_name: fastapi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_SERVER=db
      - DB_PORT=1433
      - DB_NAME=GpsDevicesDb
      - DB_USER=sa
      - DB_PASSWORD=SuperSecretPassword123!
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/uv.lock

  db:
    container_name: mssql_db
    hostname: mssql_db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1433:1433
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-C",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "SuperSecretPassword123!",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
